# Generated by Django 4.2.7 on 2026-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
            ],
            options={
                'verbose_name': '문의 메시지',
                'verbose_name_plural': '문의 메시지 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
