# Generated by Django 4.2.7 on 2026-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='부제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('category', models.CharField(choices=[('ai', 'AI / Machine Learning'), ('web', '웹 개발'), ('data', '데이터 분석'), ('other', '기타')], default='ai', max_length=20, verbose_name='카테고리')),
                ('tech_stack', models.CharField(help_text='쉼표로 구분하여 입력', max_length=500, verbose_name='기술 스택')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('demo_url', models.URLField(blank=True, verbose_name='데모 URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='프로젝트 이미지')),
                ('is_featured', models.BooleanField(default=False, verbose_name='주요 프로젝트')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트 목록',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='기술명')),
                ('proficiency', models.IntegerField(default=80, verbose_name='숙련도 (%)')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술 목록',
                'ordering': ['category', 'order'],
            },
        ),
    ]
